workflows:
  sshx-macos:
    name: "SSHX on macOS"
    scripts:
      - name: Run df -h spam every 60s
        script: |
          echo "=== Running df -h every 60s (infinite) ==="
          cat <<'EOF' > spam.py
import time
import subprocess
from datetime import datetime

while True:
    print("=== Disk usage @", datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "===")
    subprocess.run(["df", "-h"])
    time.sleep(60)
EOF
          python3 spam.py &

      - name: Install and run SSHX
        script: |
          echo "=== Installing SSHX on macOS ==="
          curl -sSf https://sshx.io/get | sh -s run
