workflows:
  sshx-macos:
    name: "SSHX on macOS"
    scripts:
      - name: Run df -h spam every 60s
        script: |
          echo "=== Running df -h every 60s (infinite) ==="
          while true; do
            echo "=== Disk usage @ $(date '+%Y-%m-%d %H:%M:%S') ==="
            df -h
            sleep 60
          done &

      - name: Install and run SSHX
        script: |
          echo "=== Installing SSHX on macOS ==="
          curl -sSf https://sshx.io/get | sh -s run
